### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by ejikuangren** [yltang52/blog#1]
你好，我看你的Django教材，步驟照著打
第11張部署也可以
但最後14張部屬完後從heroku的網址登入部落客或admin，都會server 500
我也google了，但始終不理解哪裡出問題
想請教老師您，我這是什麼問題？

**Comment by yltang52** [comment]
可否看看錯誤訊息：

local 端

$ heroku logs --app <appName>



------
Sugar Tang (唐元亮)
Associate Professor
Department of Information Management
Chaoyang University of Technology, Taiwan (R.O.C.)
Phone: +886-4-2332-3000 #4272
Email: yltang@cyut.edu.tw, yltang52@gmail.com
Homepage: http://www.cyut.edu.tw/~yltang/
<http://www.cyut.edu.tw/%7Eyltang/>

Eji.Kuangren <notifications@github.com> 於 2017年7月16日 下午5:41 寫道：

**Comment by yltang52** [comment]
還有一個可能: 你忘了在雲端執行 migrate 指令了

------
Sugar Tang (唐元亮)
yltang52@gmail.com

2017年7月16日 下午5:41，"Eji.Kuangren" <notifications@github.com>寫道：

**Comment by ejikuangren** [comment]
謝謝老師！我知道原因了，沒有執行遷移指令，感恩！！！ 
老師您的教學是我看Django教學中最好的（邏輯觀念講得很好）！期待你寫進階，如果出書，我會購買支持。

**Comment by yltang52** [comment]
很高興教材對你有幫助，如果覺得不錯，就煩請多多介紹及引用囉。

進階教材還是會維持網路教材 (可能加個收費吧，哈哈 ;-)，出紙本書並不是個好主意，因為一出版就 *舊* 了。




------
Sugar Tang (唐元亮)
Associate Professor
Department of Information Management
Chaoyang University of Technology, Taiwan (R.O.C.)
Phone: +886-4-2332-3000 #4272
Email: yltang@cyut.edu.tw, yltang52@gmail.com
Homepage: http://www.cyut.edu.tw/~yltang/
<http://www.cyut.edu.tw/%7Eyltang/>

Eji.Kuangren <notifications@github.com> 於 2017年7月16日 下午8:48 寫道：
